print('Esse programa é uma calculadora, você precisa digitar dois números e o tipo de operação.')
valor1 = int(input('Digite o primeiro número: '))
valor2 = int(input('Digite o segundo número: '))
operacao = input('Digite o operador (+ , - , * , / ):')
if operacao == '+': print(f'{valor1 + valor2}')
elif operacao == '-': print(f'{valor1 - valor2}')
elif operacao == '*': print(f'{valor1 * valor2}')
elif operacao == '/': print(f'{valor1 / valor2}')
else: print('Operador Inválido')